sources:
  - ZalandoSans.glyphs
familyName: "Zalando Sans"
version: 1.700
buildStatic: true
buildWebfont: false
autohintTTF: true
autohintOTF: true
splitItalic: true
recipeProvider: googlefonts
recipe:
# Creating a family with 3 axes
  ../fonts/variable/ZalandoSans[wdth,wght,slnt].ttf:
    - source: ZalandoSans.glyphs
    - operation: exec
      exe: fontmake
      args: -g ZalandoSans.glyphs -o variable  --output-path ../fonts/variable/ZalandoSans[wdth,wght,slnt].ttf --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    - operation: exec
      exe: gftools gen-stat
      args: ../fonts/variable/ZalandoSans[wdth,wght,slnt].ttf --src stat.yaml --inplace
    - operation: exec
      exe: gftools fix-nonhinting
      args: ../fonts/variable/ZalandoSans[wdth,wght,slnt].ttf ../fonts/variable/ZalandoSans[wdth,wght,slnt].ttf --no-backup
# Export webfont 
  ../fonts/webfonts/ZalandoSans[wdth,wght,slnt].ttf:
    - source: ZalandoSans.glyphs
    - operation: exec
      exe: fontmake
      args: -g ZalandoSans.glyphs -o variable  --output-path ../fonts/webfonts/ZalandoSans[wdth,wght,slnt].ttf --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    - operation: exec
      exe: gftools gen-stat
      args: ../fonts/webfonts/ZalandoSans[wdth,wght,slnt].ttf --src stat.yaml --inplace
    - operation: exec
      exe: gftools fix-nonhinting
      args: ../fonts/webfonts/ZalandoSans[wdth,wght,slnt].ttf ../fonts/webfonts/ZalandoSans[wdth,wght,slnt].ttf --no-backup
    - operation: exec
      exe: gftools fix-instances
      args: ../fonts/webfonts/ZalandoSans[wdth,wght,slnt].ttf -o ../fonts/webfonts/ZalandoSans[wdth,wght,slnt].ttf
    - operation: exec
      exe: pyftsubset 
      args: ../fonts/webfonts/ZalandoSans[wdth,wght,slnt].ttf --flavor=woff2 --output-file=../fonts/webfonts/ZalandoSans[wdth,wght,slnt].woff2 --glyphs=* --layout-features+=tnum --hinting --no-glyph-names
# Creating an Expanded VF and splitting the slant axis
  ../fonts/variable/ZalandoSansExpanded-Italic[wght].ttf:
    - source: ../fonts/variable/ZalandoSans[wdth,wght,slnt].ttf
    - operation: subspace
      axes: wdth=125 slnt=-10
      args: --update-name-table
    - operation: rename
      name: Zalando Sans Expanded
    - operation: fix
  ../fonts/variable/ZalandoSansExpanded[wght].ttf:
    - source: ../fonts/variable/ZalandoSans[wdth,wght,slnt].ttf
    - operation: subspace
      axes: wdth=125 slnt=0
      args: --update-name-table
    - operation: rename
      name: Zalando Sans Expanded
    - operation: fix
    - postprocess: exec
      exe: gftools gen-stat
      args: ../fonts/variable/ZalandoSansExpanded[wght].ttf ../fonts/variable/ZalandoSansExpanded-Italic[wght].ttf --src stat-1axis.yaml --inplace
# Creating an SemiExpanded VF and splitting the slant axis
  ../fonts/variable/ZalandoSansSemiExpanded-Italic[wght].ttf:
    - source: ../fonts/variable/ZalandoSans[wdth,wght,slnt].ttf
    - operation: subspace
      axes: wdth=112.5 slnt=-10
      args: --update-name-table
    - operation: rename
      name: Zalando Sans SemiExpanded
    - operation: fix
  ../fonts/variable/ZalandoSansSemiExpanded[wght].ttf:
    - source: ../fonts/variable/ZalandoSans[wdth,wght,slnt].ttf
    - operation: subspace
      axes: wdth=112.5 slnt=0
      args: --update-name-table
    - operation: rename
      name: Zalando Sans SemiExpanded
    - operation: fix
    - postprocess: exec
      exe: gftools gen-stat
      args: ../fonts/variable/ZalandoSansSemiExpanded[wght].ttf ../fonts/variable/ZalandoSansSemiExpanded-Italic[wght].ttf --src stat-1axis.yaml --inplace
    
    

