sources:
  - Zalando.glyphs
familyName: "Zalando"
version: 1.800
buildStatic: true
buildWebfont: false
autohintTTF: true
autohintOTF: true
splitItalic: true
recipeProvider: googlefonts
recipe:
# Creating a family with 3 axes
  ../fonts/variable/Zalando[wdth,wght,slnt].ttf:
    - source: Zalando.glyphs
    - operation: exec
      exe: fontmake
      args: -g Zalando.glyphs -o variable  --output-path ../fonts/variable/Zalando[wdth,wght,slnt].ttf --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    - operation: exec
      exe: gftools gen-stat
      args: ../fonts/variable/Zalando[wdth,wght,slnt].ttf --src stat.yaml --inplace
    - operation: exec
      exe: gftools fix-nonhinting
      args: ../fonts/variable/Zalando[wdth,wght,slnt].ttf ../fonts/variable/Zalando[wdth,wght,slnt].ttf --no-backup
# Export webfont 
  ../fonts/webfonts/Zalando[wdth,wght,slnt].ttf:
    - source: Zalando.glyphs
    - operation: exec
      exe: fontmake
      args: -g Zalando.glyphs -o variable  --output-path ../fonts/webfonts/Zalando[wdth,wght,slnt].ttf --filter ... --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    - operation: exec
      exe: gftools gen-stat
      args: ../fonts/webfonts/Zalando[wdth,wght,slnt].ttf --src stat.yaml --inplace
    - operation: exec
      exe: gftools fix-nonhinting
      args: ../fonts/webfonts/Zalando[wdth,wght,slnt].ttf ../fonts/webfonts/Zalando[wdth,wght,slnt].ttf --no-backup
    - operation: exec
      exe: gftools fix-instances
      args: ../fonts/webfonts/Zalando[wdth,wght,slnt].ttf -o ../fonts/webfonts/Zalando[wdth,wght,slnt].ttf
    - operation: exec
      exe: pyftsubset 
      args: ../fonts/webfonts/Zalando[wdth,wght,slnt].ttf --flavor=woff2 --output-file=../fonts/webfonts/Zalando[wdth,wght,slnt].woff2 --glyphs=* --layout-features+=tnum --hinting --no-glyph-names
# Creating an Expanded VF and splitting the slant axis
  ../fonts/variable/ZalandoExpanded-Italic[wght].ttf:
    - source: ../fonts/variable/Zalando[wdth,wght,slnt].ttf
    - operation: subspace
      axes: wdth=125 slnt=-10
      args: --update-name-table
    - operation: rename
      name: Zalando Expanded
    - operation: fix
  ../fonts/variable/ZalandoExpanded[wght].ttf:
    - source: ../fonts/variable/Zalando[wdth,wght,slnt].ttf
    - operation: subspace
      axes: wdth=125 slnt=0
      args: --update-name-table
    - operation: rename
      name: Zalando Expanded
    - operation: fix
    - postprocess: exec
      exe: gftools gen-stat
      args: ../fonts/variable/ZalandoExpanded[wght].ttf ../fonts/variable/ZalandoExpanded-Italic[wght].ttf --src stat-1axis.yaml --inplace
# Creating an SemiExpanded VF and splitting the slant axis
  ../fonts/variable/ZalandoSemiExpanded-Italic[wght].ttf:
    - source: ../fonts/variable/Zalando[wdth,wght,slnt].ttf
    - operation: subspace
      axes: wdth=112.5 slnt=-10
      args: --update-name-table
    - operation: rename
      name: Zalando SemiExpanded
    - operation: fix
  ../fonts/variable/ZalandoSemiExpanded[wght].ttf:
    - source: ../fonts/variable/Zalando[wdth,wght,slnt].ttf
    - operation: subspace
      axes: wdth=112.5 slnt=0
      args: --update-name-table
    - operation: rename
      name: Zalando SemiExpanded
    - operation: fix
    - postprocess: exec
      exe: gftools gen-stat
      args: ../fonts/variable/ZalandoSemiExpanded[wght].ttf ../fonts/variable/ZalandoSemiExpanded-Italic[wght].ttf --src stat-1axis.yaml --inplace
    
    

